# Base Image 

FROM ubuntu:16.04

RUN apt-get update 

RUN apt-get install apache2 -y 

COPY info.html /var/www/html/info.html 

EXPOSE 80
EXPOSE 3306

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
